#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
shopt -s nullglob nocaseglob

# modern bash version check
! [ "${BASH_VERSINFO:-0}" -ge 4 ] && echo "This script requires bash v4 or later" && exit 1

# path to self and parent dir
SCRIPT=$(realpath $0)
SCRIPTPATH=$(dirname $SCRIPT)

# check for lima binary
if ! command -v limactl &> /dev/null
then
    echo "limactl could not be found"
    echo "Install lima from https://lima-vm.io/docs/installation/"
    exit 1
fi

# update sha256 from web
CURRENT_HASH=$(wget -qO- https://cloud-images.ubuntu.com/noble/current/SHA256SUMS | grep arm64.img | awk '{print $1}')

# update the digest in the yaml file
sed -i '' "s/digest: .*/digest: \"sha256:${CURRENT_HASH}\"/" "${SCRIPTPATH}/macsl.yaml"

# if ~/.lima/noble/lima.yaml do a reset otherwise create a new instance
if [ -f ~/.lima/noble/lima.yaml ]; then
  echo "limactl factory-reset noble"
  limactl factory-reset noble
  cp "${SCRIPTPATH}/macsl.yaml" ~/.lima/noble/lima.yaml
else
  echo "limactl create --name=noble macsl.yaml"
  limactl create --name=noble macsl.yaml
fi

# start the instance and build the image
echo "limactl start noble"
limactl start noble

exit 0
