#!/usr/bin/env bash
IFS=$'\n\t'
shopt -s nullglob nocaseglob

# read env vars
if [[ $LAUNCHD_MODE == 1 ]]; then
  echo "Launchd Mode enabled"
else
  LAUNCHD_MODE=0
fi

# Set strict mode after reading env vars
set -euo pipefail

# modern bash version check
! [ "${BASH_VERSINFO:-0}" -ge 4 ] && echo "This script requires bash v4 or later" && exit 1

# Define global variables and set defaults
VM_BOOT=0
LAUNCHD_SETUP=0
VM_REBOOT=0
VM_SHUTDOWN=0
VM_PATH=0
VM_IP=0

# read defaults from config
if [[ -f "${HOME}/.macsl" ]]; then
  source "${HOME}/.macsl"
fi

# print out usage
usage() {
  cat <<EOF
USAGE: ./macsl -b -v ~/vm/linux.vmx
OPTIONS:
   -l    Setup launchd
   -b    Boot up the VM
   -r    Rebot the VM
   -s    Shutdown the VM
   -v    Path to vmx file
   -i    Output the VM IP
   -h    Help
EOF
  exit 0
}

# process options and arguments
while getopts "lbrsv:ih" OPTION; do
  case $OPTION in
  l) LAUNCHD_SETUP=1 ;;
  b) VM_BOOT=1 ;;
  r) VM_REBOOT=1 ;;
  s) VM_SHUTDOWN=1 ;;
  v) VM_PATH="$OPTARG" ;;
  i) VM_IP=1 ;;
  h) usage && exit 0 ;;
  *) usage && exit 0 ;;
  esac
done

# catch no options
if [[ $(($LAUNCHD_SETUP + $VM_BOOT + $VM_SHUTDOWN + $VM_IP + $VM_REBOOT + $LAUNCHD_MODE)) == "0" ]]; then
  usage && exit 0
fi

# path to self and parent dir
#SCRIPT=$(realpath "$0")
#SCRIPTPATH=$(dirname "$SCRIPT")

# functions for doing the stuff
launchd_setup() {
  echo "LAUNCHD SETUP"
  tee ${HOME}/Library/LaunchAgents/com.blakegarner.macsl.plist >/dev/null <<-PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>EnvironmentVariables</key>
  <dict>
    <key>LAUNCHD_MODE</key>
    <string>1</string>
    <key>PATH</key>
    <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/usr/local/share/dotnet:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/sbin</string>
  </dict>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <true/>
  </dict>
  <key>Label</key>
  <string>com.blakegarner.macsl</string>
  <key>ProgramArguments</key>
  <array>
    <string>$HOME/code/macsl/macsl</string>
    <string>-v</string>
    <string>$VM_PATH</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>StandardOutPath</key>
  <string>/Users/blake/Library/Logs/com.blakegarner.macsl.log</string>
  <key>StandardErrorPath</key>
  <string>$HOME/Library/Logs/com.blakegarner.macsl.log</string>
</dict>
</plist>
PLIST
  launchctl load -w ${HOME}/Library/LaunchAgents/com.blakegarner.macsl.plist
}

# launchd mode
launchd_mode() {
  trap "echo trapped EXIT && vm_shutdown && break" EXIT
  trap "echo trapped SIGHUP && vm_shutdown && break" SIGHUP
  trap "echo trapped SIGINT && vm_shutdown && break" SIGINT
  trap "echo trapped SIGTERM && vm_shutdown && break" SIGTERM
  vm_boot
  while :; do
    echo "macsl loop started"
    sleep 86400
  done
  # setup traps for restart and shutdown
  # start loop
  # startup macsl VM
  # on shutdown signal stop vm & exit clean
  # on restart signal restart vm
}

vm_boot() {
  echo "VM BOOT"
  vmrun start "$VM_PATH" nogui
}

vm_reboot() {
  echo "VM REBOOT"
  vmrun reset "$VM_PATH" hard
}

vm_shutdown() {
  echo "VM SHUTDOWN"
  vmrun stop "$VM_PATH" soft
}

vm_path() {
  # echo "VM PATH: $VM_PATH"
  if [[ ! -f "$VM_PATH" ]]; then
    echo "The path $VM_PATH is not valid"
    usage
    exit 1
  fi

  if ! [[ "$VM_PATH" =~ .*\.vmx ]]; then
    echo "The file $(basename $VM_PATH) does not have a .vmx extention"
    usage
    exit 1
  fi
}

vm_ip() {
  echo "VM IP"
  vmrun getGuestIPAddress $VM_PATH
}

# script flow logic
if [[ $LAUNCHD_MODE != 0 ]]; then
  echo "Launchd Mode"
  launchd_mode
fi

if [[ $VM_PATH != 0 ]]; then
  echo "running vm path"
  vm_path
fi

if [[ $LAUNCHD_SETUP == 1 ]]; then
  launchd_setup
fi

if [[ $VM_BOOT == 1 ]]; then
  vm_boot
fi

if [[ $VM_REBOOT == 1 ]]; then
  vm_reboot
fi

if [[ $VM_SHUTDOWN == 1 ]]; then
  vm_shutdown
fi

if [[ $VM_IP == 1 ]]; then
  vm_ip
fi

echo "End of Line..."
exit 0
