# listen_port nfigures the UDP port that the AURP server will listen on.
# Optional; defaults to 387 (the traditional AURP port).
# If you are operating behind a NAT, this can be any port you can forward to,
# but if jrouter is exposed directly to the internet, only 387 is expected to
# work.
listen_port: 387

# local_ip is used to set the "real" IP address that this server is
# reachable on, when it is not any of the host addresses.
# AURP includes this address as part of this server's identity in the network.
#
# (Say jrouter is running behind NAT, it won't know what the real publicly-
# routable address of the NAT gateway is unless you set this.)
#
# This is technically optional.
local_ip: 207.108.197.152

# monitoring_addr enables an inbuilt HTTP server that serves endpoints related
# to monitoring jrouter. Currently these are:
# - /status - a page that displays the current state of key components
# - /metrics - Prometheus-style metrics
monitoring_addr: ":9459"

# ethertalk configures network interfaces used for Ethertalk, and the
# AppleTalk zone information.
# This can contain either a single ethertalk config, or a list of such configs.
ethertalk:
  - device: lima0 # Name of the device - required.
    # ethernet_addr overrides the "hardware" address used by jrouter.
    # This is useful if you have another AppleTalk software running on the same
    # machine, e.g. netatalk, and you do not want jrouter to steal its packets.
    ethernet_addr: '52:55:55:66:0b:88'
    # Name of the AppleTalk zone - required.
    zone_name: netjibbing
    # Network number range for this network (inclusive) - required.
    net_start: 650
    net_end: 650

# open_peering lets the server accept incoming connections from unknown servers.
# If you disable this, only the configured peers will be connected.
open_peering: true

# peers lists IP addresses or domain names of peers to actively connect to.
#peers:
#  - 192.0.2.1
#  - example.net

# peerlist_url provides an address to download a plain-text file containing
# peers to actively connect to.
peerlist_url: http://kalleboo.com/GT2024.txt


